[theme]
base = "dark"
primaryColor = "#02C076"
backgroundColor = "#111417"
secondaryBackgroundColor = "#181A20"
textColor = "#E1E2E7"
font = "sans serif"

[server]
headless = true
port = 20001
enableXsrfProtection = true

[browser]
gatherUsageStats = false
